name: 'Cleanup build cache'
description: 'Cleanup gradle build cache'
runs:
  using: "composite"
  steps:
    - name: Stop gradle daemon
        run: ./gradlew --stop

    - name: Cleanup Gradle Cache Posix
      if: runner.os != 'Windows'
      run: |
        rm -f ~/.gradle/caches/modules-2/modules-2.lock
        rm -f ~/.gradle/caches/modules-2/gc.properties

    - name: Cleanup Gradle Cache Windows
      if: runner.os == 'Windows'
      run: |
        if (test-path ~/.gradle/caches/modules-2/modules-2.lock) { rm ~/.gradle/caches/modules-2/modules-2.lock }
        if (test-path ~/.gradle/caches/modules-2/gc.properties) { rm ~/.gradle/caches/modules-2/gc.properties }