name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, reopened, synchronize, labeled, unlabeled ]

jobs:


  find-version:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    outputs:
      snapshot: ${{ (endsWith(steps.get_version.outputs.match, 'SNAPSHOT') || endsWith(steps.get_version.outputs.match, 'snapshot')) }}
      version: ${{ steps.get_version.outputs.match }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Grant execute permission for gradlew
        run: |
          chmod +x gradlew
          chmod +x tests/gradlew

      - name: Get version
        if: github.ref == 'refs/heads/main'
        id: get_version
        uses: rnett/find-regex@v1.2
        with:
          regex: 'version ?(?:=|:) ?"?([\w.\-_]+)"?'
          files: "build.gradle.kts,gradle.properties,build.gradle"
          commands: "./gradlew properties"

  create_staging_repository:
    runs-on: ubuntu-latest
    needs: [ find-version ]
    name: Create staging repository
    if: github.ref == 'refs/heads/main'
    outputs:
      repository_id: ${{ steps.create.outputs.repository_id }}
    steps:
      - name: Print version
        run: |
          echo "Snapshot string: ${{ needs.find-version.outputs.snapshot }}"
          echo "Is release: ${{ needs.find-version.outputs.snapshot == 'false' }}"
      - id: create
        if: needs.find-version.outputs.snapshot == 'false'
        uses: nexus-actions/create-nexus-staging-repo@v1.1
        with:
          username: rnett
          password: ${{ secrets.SONATYPE_PASSWORD }}
          staging_profile_id: ${{ secrets.SONATYPE_PROFILE_ID }}
          description: ${{ github.repository }}/${{ github.workflow }}#${{ github.run_number }} - ${{ needs.find-version.outputs.version }}

  build:
    needs: [ create_staging_repository ]
    if: always()
    strategy:
      matrix:
        os: [ ubuntu, mac, windows ]
        include:
          - os: ubuntu
            runner: ubuntu-latest
          - os: mac
            runner: macOS-11
          - os: windows
            runner: windows-latest
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    name: Build, Test, and Publish (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Install CURL headers Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y
          sudo apt-get install libcurl4-openssl-dev -y

      - name: Grant execute permission for gradlew
        run: |
          chmod +x gradlew
          chmod +x tests/gradlew

      - name: Build and Unit Test
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-includes: |
            nodejs
            yarn
            ../konan
          arguments: build check

      - name: Run Integraiton Tests
        uses: gradle/gradle-build-action@v2
        env:
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
        with:
          gradle-home-cache-includes: |
            nodejs
            yarn
            ../konan
          build-root-directory: ./tests
          arguments: check

      - name: Upload test reports
        uses: actions/upload-artifact@v2
        with:
          name: test-report-${{ runner.os }}
          path: "**/build/reports/tests/**"

      - name: Publish
        if: github.ref == 'refs/heads/main'
        uses: gradle/gradle-build-action@v2
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: rnett
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          ORG_GRADLE_PROJECT_sonatypeRepositoryId: ${{ needs.create_staging_repository.outputs.repository_id }}
          GRADLE_OPTS: -Xmx4096m
        with:
          gradle-home-cache-includes: |
            nodejs
            yarn
            ../konan
          arguments: publish


  publish-docs:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [ find-version, build ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Grant execute permission for gradlew
        run: |
          chmod +x gradlew
          chmod +x tests/gradlew

      - name: Clone past docs for release
        if: needs.find-version.outputs.snapshot == 'false'
        run: |
          git fetch
          git clone --depth 1 https://github.com/rnett/krosstalk.git --branch gh-pages --single-branch past-docs
          mkdir -p past-docs/old-releases/core
          mkdir -p past-docs/old-releases/plugins

      - name: Remove current docs from old docs
        run: |
          rm -rf past-docs/old-releases/core/${{ needs.find-version.outputs.version }}
          rm -rf past-docs/old-releases/core/*/older

          rm -rf past-docs/old-releases/plugins/${{ needs.find-version.outputs.version }}
          rm -rf past-docs/old-releases/plugins/*/older

      - name: List core versions
        if: needs.find-version.outputs.snapshot == 'false'
        run: ls -l past-docs/old-releases/core
      - name: List plugin versions
        if: needs.find-version.outputs.snapshot == 'false'
        run: ls -l past-docs/old-releases/plugins

      - name: Generate HTML Docs and README
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-includes: |
            nodejs
            yarn
            ../konan
          arguments: generateReadme dokkaHtmlMultiModule -PgitBranch=$GITHUB_SHA -PcoreVersionDir=past-docs/old-releases/core -PpluginVersionDir=past-docs/old-releases/plugins -DRELEASE_SIGNING_ENABLED=false

      - name: Publish Core docs
        uses: rnett/publish-docs@v2.6
        with:
          from: core/build/dokka/htmlMultiModule
          publish-to: '$latest/core,!old-releases/core/$version'
          version: ${{ needs.find-version.outputs.version }}
          restore: true
          message: Update Core docs for $version

      - name: Publish Plugin docs
        uses: rnett/publish-docs@v2.6
        with:
          from: plugins/build/dokka/htmlMultiModule
          publish-to: '$latest/plugins,!old-releases/plugins/$version'
          version: ${{ needs.find-version.outputs.version }}
          restore: true
          message: Update Plugin docs for $version

      - name: Publish README
        uses: rnett/publish-docs@v2.6
        with:
          from-file: ./build/README.md
          publish-to: '$latest,!.'
          version: ${{ needs.find-version.outputs.version }}
          restore: true
          message: Update README for $version

  finalize:
    runs-on: ubuntu-latest
    needs: [ create_staging_repository, find-version, build, publish-docs ]
    if: ${{ always() && needs.create_staging_repository.result == 'success' && needs.find-version.outputs.snapshot == 'false' }}
    steps:
      - name: Discard
        if: ${{ needs.publish-docs.result != 'success' }}
        uses: nexus-actions/drop-nexus-staging-repo@v1
        with:
          username: rnett
          password: ${{ secrets.SONATYPE_PASSWORD }}
          staging_repository_id: ${{ needs.create_staging_repository.outputs.repository_id }}
      - name: Release
        if: ${{ needs.publish-docs.result == 'success' }}
        uses: nexus-actions/release-nexus-staging-repo@v1.2
        with:
          username: rnett
          password: ${{ secrets.SONATYPE_PASSWORD }}
          staging_repository_id: ${{ needs.create_staging_repository.outputs.repository_id }}
          description: Closed ${{ github.repository }}/${{ github.workflow }}#${{ github.run_number }} - ${{ needs.find-version.outputs.version }}
          close_only: 'true'
