name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: |
          chmod +x gradlew
          chmod +x tests/gradlew

      - name: Build and Unit Test
        run: ./gradlew build -DRELEASE_SIGNING_ENABLED=false # test allTests

      #      - name: Run Integraiton Tests
      #        run: (cd tests && ./gradlew allTests)

      - name: Get version
        if: github.ref == 'refs/heads/main'
        id: get_version
        uses: rnett/find-regex@v1.1
        with:
          regex: 'version ?(?:=|:) ?"?([\w.\-_]+)"?'
          files: "build.gradle.kts,gradle.properties,build.gradle"
          commands: "./gradlew properties"

      - name: Set release/snapshot
        run: |
          if [[ "${{ steps.get_version.outputs.match }}" == *SNAPSHOT ]]
          then
              version="snapshot"
          else
              version="release"
          fi
          echo "version=$version" >> $GITHUB_ENV

      - name: Clone past docs for release
        if: env.version == 'release'
        run: git clone --depth 1 https://github.com/rnett/krosstalk.git --branch gh-pages --single-branch past-docs

      - name: Generate HTML Docs
        run: ./gradlew dokkaHtmlMultiModule -PsourceLinkBranch=$GITHUB_SHA -PversionDir=past-docs/release


      #      - id: install_gpg_key
      #        if: github.ref == 'refs/heads/main'
      #        name: Install gpg secret key
      #        uses: rnett/import-gpg-key@v1.1
      #        with:
      #          secret-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
      #          export-secring: true
      #      - name: Publish
      #        if: github.ref == 'refs/heads/main'
      #        env:
      #          ORG_GRADLE_PROJECT_mavenCentralRepositoryPassword: ${{ secrets.SONATYPE_PASSWORD }}
      #          ORG_GRADLE_PROJECT_mavenCentralRepositoryUsername: ${{ secrets.SONATYPE_USERNAME }}
      #          GRADLE_OPTS: -Xmx2048m -XX:MaxPermSize=512m
      #        run: ./gradlew publish --no-daemon --no-parallel -Psigning.keyId=${{steps.install_gpg_key.outputs.key-id}} -Psigning.secretKeyRingFile=/home/runner/.gnupg/secring.gpg -Psigning.password=${{ secrets.OSSRH_GPG_KEY_PASSWORD }}

      - name: Stop gradle daemon
        run: ./gradlew --stop
      - name: Publish docs
        if: github.ref == 'refs/heads/main'
        uses: rnett/publish-docs@v1.6-pre4
        with:
          from: build/dokka/htmlMultiModule
          publish-to: ${{ env.version }}
          restore: 'false'